version: '3'

networks:
  elastic:
    driver: bridge

services:

  zookeeper-1:
    networks:
      - elastic
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  zookeeper-2:
    networks:
      - elastic
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 32181:2181

  kafka-1:
    networks:
      - elastic
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper-1
      - zookeeper-2
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-2:
    networks:
      - elastic
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper-1
      - zookeeper-2
    ports:
      - 39092:39092
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092,PLAINTEXT_HOST://localhost:39092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  postgres-read:
    image: postgres:latest
    container_name: postgres-read
    environment:
      POSTGRES_PASSWORD: test123
    ports:
      - "5431:5432"
    volumes:
      - postgres-read:/var/lib/postgresql/data
  postgres-write:
    image: postgres:latest
    container_name: postgres-write
    environment:
      POSTGRES_PASSWORD: test123
    ports:
      - "5432:5432"
    volumes:
      - postgres-write:/var/lib/postgresql/data
  memcached:
    image: memcached:latest
    container_name: memcached
    ports:
      - "11211:11211"

  kafkaui:
    networks:
      - elastic
    depends_on:
      - kafka-1
      - kafka-2
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8000:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: kafka-1
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka-1:9092"
      DYNAMIC_CONFIG_ENABLED: 'true'
volumes:
  postgres-read:
  postgres-write:
