global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: prometheus
    static_configs:
     - targets: ["localhost:9090"]

  - job_name: byoc
      # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    metrics_path: /management/prometheus
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
     - targets: ["host.docker.internal:8080"]

  - job_name: helm
      # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    metrics_path: /management/prometheus
    static_configs:
     - targets: ["host.docker.internal:8082"]